#!/bin/sh
#
# lighttpd     Startup script for the lighttpd server
#
# chkconfig: - 85 15
# description: Lightning fast webserver with light system requirements
#
# processname: lighttpd
# config: /etc/lighttpd/lighttpd.conf
# config: /etc/sysconfig/lighttpd
# pidfile: /var/run/lighttpd.pid
#
# Note: pidfile is assumed to be created
# by lighttpd (config: server.pid-file).
# If not, uncomment 'pidof' line.

if [ -z "$LIGHTTPD_CONF_PATH" ]; then
	LIGHTTPD_CONF_PATH="/etc/lighttpd/lighttpd.conf"
fi

NAME=lighttpd
DAEMON=/usr/sbin/$NAME
PIDFILE=/var/run/$NAME.pid
RETVAL=0

start() {
    echo -n "Starting $NAME: "
    start-stop-daemon -S -q -p $PIDFILE --exec $DAEMON -- -f $LIGHTTPD_CONF_PATH && echo "OK" || echo "Failed"
}

stop() {
    echo -n "Stopping $NAME: "
    start-stop-daemon -K -q -p $PIDFILE && echo "OK" || echo "Failed"
    rm -f $PIDFILE
}

restart() {
	stop
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	restart|reload)
		restart
		;;
	*)
		echo $"Usage: $0 {start|stop|restart|reload}"
		RETVAL=1
esac

exit $RETVAL
