#!/bin/sh

[ -x /usr/bin/imageserver ] || exit 0

case "$1" in
	start)
		echo -n "Starting imageserver: "
		start-stop-daemon -Sb -x /usr/bin/imageserver
		[ $? == 0 ] && echo "OK" || echo "FAIL"
		;;
	stop)
		echo -n "Stopping imageserver: "
		start-stop-daemon -K -x /usr/bin/imageserver
		[ $? == 0 ] && echo "OK" || echo "FAIL"
		;;
	restart|reload)
		$0 stop
		$0 start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit 0
